version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 20
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python src/forgebase/interfaces/web.py
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    depends_on:
      backend:
        condition: service_healthy

networks:
  default:
    name: forgebase-network
