[tool.black]
line-length = 88

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "semantic_kernel.*"
ignore_errors = true

[tool.pytest.ini_options]
pythonpath = [
  "src"
]