import React from 'react';
import { Box, Container, ScrollArea, Title, Text, Stack } from '@mantine/core';

interface PrdPreviewProps {
    projectId: string;
}

export const PrdPreview: React.FC<PrdPreviewProps> = ({ projectId }) => {
    // For now, using simple mock content - later this will be generated by AI
    return (
        <Box style={{ height: '100%', display: 'flex', flexDirection: 'column' }}>
            <ScrollArea style={{ flex: 1 }} p="md">
                <Container size="lg">
                    <Stack gap="lg">
                        <Title order={1}>Product Requirements Document</Title>
                        
                        <Box>
                            <Title order={2} mb="sm">Project Overview</Title>
                            <Text>
                                This is a comprehensive Product Requirements Document for project {projectId}. 
                                This document outlines the key requirements, features, and specifications 
                                for an innovative e-commerce platform.
                            </Text>
                        </Box>
                        
                        <Box>
                            <Title order={2} mb="sm">Executive Summary</Title>
                            <Text>
                                Our goal is to create a modern, user-friendly e-commerce platform that 
                                provides seamless shopping experiences across all devices while maintaining 
                                high performance and security standards.
                            </Text>
                        </Box>
                        
                        <Box>
                            <Title order={2} mb="sm">User Stories</Title>
                            <Text fw={600} mb="xs">As a Customer</Text>
                            <Text mb="xs">• I want to browse products easily so that I can find what I'm looking for quickly</Text>
                            <Text mb="xs">• I want to add items to my cart so that I can purchase multiple items at once</Text>
                            <Text mb="xs">• I want to checkout securely so that my payment information is protected</Text>
                            <Text mb="xs">• I want to track my orders so that I know when to expect delivery</Text>
                            
                            <Text fw={600} mb="xs" mt="md">As an Admin</Text>
                            <Text mb="xs">• I want to manage inventory so that customers see accurate stock levels</Text>
                            <Text mb="xs">• I want to process orders efficiently so that customers receive their items quickly</Text>
                            <Text mb="xs">• I want to view sales analytics so that I can make informed business decisions</Text>
                        </Box>
                        
                        <Box>
                            <Title order={2} mb="sm">Technical Requirements</Title>
                            <Text fw={600} mb="xs">Performance</Text>
                            <Text mb="xs">• Page load times should be under 2 seconds</Text>
                            <Text mb="xs">• The platform should handle 10,000 concurrent users</Text>
                            <Text mb="xs">• 99.9% uptime SLA</Text>
                            
                            <Text fw={600} mb="xs" mt="md">Security</Text>
                            <Text mb="xs">• PCI DSS compliance for payment processing</Text>
                            <Text mb="xs">• SSL encryption for all data transmission</Text>
                            <Text mb="xs">• Two-factor authentication for admin accounts</Text>
                        </Box>
                        
                        <Box>
                            <Title order={2} mb="sm">Core Features</Title>
                            <Text fw={600} mb="xs">Product Catalog</Text>
                            <Text mb="xs">• Search and filtering capabilities</Text>
                            <Text mb="xs">• Product recommendations</Text>
                            <Text mb="xs">• Product comparison tool</Text>
                            
                            <Text fw={600} mb="xs" mt="md">Shopping Cart</Text>
                            <Text mb="xs">• Persistent cart across sessions</Text>
                            <Text mb="xs">• Save for later functionality</Text>
                            <Text mb="xs">• Promotional code support</Text>
                        </Box>
                        
                        <Box>
                            <Title order={2} mb="sm">Success Metrics</Title>
                            <Text mb="xs">• Conversion rate improvement of 25%</Text>
                            <Text mb="xs">• Cart abandonment rate below 15%</Text>
                            <Text mb="xs">• Customer satisfaction score above 4.5/5</Text>
                            <Text mb="xs">• Mobile traffic representing 60% of total visits</Text>
                        </Box>
                    </Stack>
                </Container>
            </ScrollArea>
        </Box>
    );
};
